//====== periodica/rust/periodica_core/tests/derived_regeneration.rs ======//
//!copyright (c) 2025 Andrew Keith Watts. All rights reserved.
//!
//!This is the intellectual property of Andrew Keith Watts. Unauthorized
//!reproduction, distribution, or modification of this code, in whole or in part,
//!without the express written permission of Andrew Keith Watts is strictly prohibited.
//!
//!For inquiries, please contact AndrewKWatts@Gmail.com

//! Every committed `data/derived/` entry must be exactly what the native
//! composer produces from `scripts/inputs/*.json`.
//!
//! The derived tiers are generated by `scripts/build_*.py`. Until those
//! scripts call the native composer directly, they run the Python twin of the
//! composer and of the curated-mass step (`scripts/_mass_source.py`); this
//! test regenerates every row with the Rust implementation -- compose, curated
//! mass, row enrichments, `Name` -- and compares, so the two implementations
//! cannot drift apart and the committed data cannot go stale.

use std::path::{Path, PathBuf};

use periodica_core::data_loader;
use periodica_core::get::{get, Spec};
use periodica_core::mass_source::MassSources;
use periodica_core::periodica_mat::jsonc;
use periodica_core::rules::CompositionRules;
use serde_json::Value;

fn data_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../src/periodica/data")
}

fn inputs_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../src/periodica/scripts/inputs")
}

/// JSON equality with a relative tolerance on floats: the committed files are
/// written by Python's shortest-repr float formatter and parsed back here.
fn same(a: &Value, b: &Value, path: &str, diffs: &mut Vec<String>) {
    match (a, b) {
        (Value::Object(x), Value::Object(y)) => {
            let mut keys: Vec<&String> = x.keys().chain(y.keys()).collect();
            keys.sort();
            keys.dedup();
            for k in keys {
                match (x.get(k), y.get(k)) {
                    (Some(p), Some(q)) => same(p, q, &format!("{path}.{k}"), diffs),
                    _ => diffs.push(format!("{path}.{k}: present on one side only")),
                }
            }
        }
        (Value::Array(x), Value::Array(y)) if x.len() == y.len() => {
            for (i, (p, q)) in x.iter().zip(y).enumerate() {
                same(p, q, &format!("{path}[{i}]"), diffs);
            }
        }
        (Value::Number(x), Value::Number(y)) => {
            let ints_differ = x.is_f64() != y.is_f64();
            let (p, q) = (x.as_f64().unwrap(), y.as_f64().unwrap());
            let close = p == q || ((p - q) / p.abs().max(q.abs())).abs() <= 1e-14;
            if ints_differ || !close {
                diffs.push(format!("{path}: native {x} vs committed {y}"));
            }
        }
        _ if a == b => {}
        _ => diffs.push(format!("{path}: native {a} vs committed {b}")),
    }
}

fn scope_of(from: Option<&Value>) -> Option<Vec<String>> {
    match from {
        None | Some(Value::Null) => None,
        Some(Value::String(s)) => Some(vec![s.clone()]),
        Some(Value::Array(a)) => Some(a.iter().filter_map(|v| v.as_str().map(str::to_string)).collect()),
        Some(other) => panic!("unsupported `from`: {other}"),
    }
}

#[test]
fn derived_tiers_are_reproduced_by_the_native_composer() {
    let data = data_dir();
    if !data.is_dir() {
        eprintln!("skipping: bundled data not present");
        return;
    }
    data_loader::load_all_tiers(&data).expect("load");
    let rules = CompositionRules::load(&data).expect("rules");
    let masses = MassSources::load(&rules, &data).expect("mass sources").expect("declared");

    let mut inputs: Vec<PathBuf> = std::fs::read_dir(inputs_dir())
        .expect("inputs dir")
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|x| x.to_str()) == Some("json"))
        .collect();
    inputs.sort();
    assert!(inputs.len() >= 9, "{inputs:?}");

    let mut checked = 0usize;
    let mut failures = Vec::new();
    for input in &inputs {
        let doc = jsonc::from_path(input).expect("input json");
        let tier = doc["tier"].as_str().unwrap_or("general").to_string();
        let scope = scope_of(doc.get("from"));
        let scope_refs: Option<Vec<&str>> = scope.as_ref().map(|s| s.iter().map(String::as_str).collect());
        for row in doc["rows"].as_array().expect("rows") {
            let name = row["name"].as_str().expect("row name");
            let spec: Vec<(String, Value)> = row["spec"]
                .as_object()
                .expect("spec map")
                .iter()
                .map(|(k, v)| (k.clone(), v.clone()))
                .collect();

            let mut native = match get(Spec::Map(&spec), scope_refs.as_deref()) {
                Ok(v) => v,
                Err(e) => {
                    failures.push(format!("{tier}/{name}: native compose failed: {e}"));
                    continue;
                }
            };
            masses.apply(&tier, &mut native).expect("mass source");
            let obj = native.as_object_mut().unwrap();
            if let Some(sym) = row.get("symbol").and_then(Value::as_str).filter(|s| !s.is_empty()) {
                obj.insert("Symbol".into(), Value::String(sym.to_string()));
            }
            for (key, field) in [("properties", "Properties"), ("field", "Field")] {
                if let Some(v) = row.get(key).filter(|v| v.as_object().is_some_and(|o| !o.is_empty())) {
                    obj.insert(field.into(), v.clone());
                }
            }
            if let Some(v) = row.get("aliases").filter(|v| v.as_array().is_some_and(|a| !a.is_empty())) {
                obj.insert("Aliases".into(), v.clone());
            }
            obj.entry("Name").or_insert_with(|| Value::String(name.to_string()));

            let file = data.join("derived").join(&tier).join(format!("{name}.json"));
            let committed = match jsonc::from_path(&file) {
                Ok(v) => v,
                Err(e) => {
                    failures.push(format!("{}: {e}", file.display()));
                    continue;
                }
            };
            let mut diffs = Vec::new();
            same(&native, &committed, &format!("{tier}/{name}"), &mut diffs);
            failures.extend(diffs);
            checked += 1;
        }
    }
    assert!(checked >= 300, "only {checked} rows checked");
    assert!(
        failures.is_empty(),
        "{} differences between the native composer and the committed derived data \
         (regenerate with `python -m periodica build`):\n{}",
        failures.len(),
        failures.iter().take(40).cloned().collect::<Vec<_>>().join("\n")
    );
}
