"""
Derivation Metadata System
===========================
Tracks provenance of all derived data in the Periodics system.
Every JSON data item can be stamped with derivation metadata,
recording where the data came from, what it was derived from,
and how confident the derivation is.

Convention: metadata is stored under the "_derivation" key in JSON dicts,
following the existing "_filename" pattern used by DataManager.
"""

from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional


class DerivationSource(Enum):
    """How a data item was created."""
    QUARK_DERIVED = "quark_derived"       # Derived from quark constants
    PHYSICS_DERIVED = "physics_derived"   # Derived from physics calculations
    MANUAL = "manual"                     # Manually entered/edited by user
    LOADED_DEFAULT = "loaded_default"     # Loaded from defaults directory
    AI_GENERATED = "ai_generated"         # Generated by AI (Gemini etc.)
    AUTO_GENERATED = "auto_generated"     # Auto-generated by combinatorial engine


@dataclass
class DerivationMetadata:
    """Provenance metadata for a derived data item."""
    source: str  # DerivationSource value
    derived_from: List[str] = field(default_factory=list)  # upstream entity IDs
    derivation_chain: List[str] = field(default_factory=list)  # steps taken
    confidence: float = 1.0  # 0.0 to 1.0
    timestamp: str = ""  # ISO format
    model_version: str = "1.0.0"

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.now(timezone.utc).isoformat()

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'DerivationMetadata':
        """Create from dictionary."""
        return cls(
            source=data.get('source', DerivationSource.MANUAL.value),
            derived_from=data.get('derived_from', []),
            derivation_chain=data.get('derivation_chain', []),
            confidence=data.get('confidence', 1.0),
            timestamp=data.get('timestamp', ''),
            model_version=data.get('model_version', '1.0.0'),
        )


class DerivationTracker:
    """
    Stamps data dicts with derivation metadata and provides
    utilities for querying derivation state.
    """

    METADATA_KEY = "_derivation"

    @staticmethod
    def stamp(
        data: Dict,
        source: DerivationSource,
        derived_from: Optional[List[str]] = None,
        derivation_chain: Optional[List[str]] = None,
        confidence: float = 1.0,
        model_version: str = "1.0.0",
    ) -> Dict:
        """
        Stamp a data dict with derivation metadata.

        Args:
            data: The data dict to stamp
            source: How this data was created
            derived_from: List of upstream entity identifiers
            derivation_chain: List of derivation steps
            confidence: Confidence score 0.0-1.0
            model_version: Version of the derivation model

        Returns:
            The data dict with _derivation key added
        """
        metadata = DerivationMetadata(
            source=source.value,
            derived_from=derived_from or [],
            derivation_chain=derivation_chain or [],
            confidence=confidence,
            model_version=model_version,
        )
        data[DerivationTracker.METADATA_KEY] = metadata.to_dict()
        return data

    @staticmethod
    def get_metadata(data: Dict) -> Optional[DerivationMetadata]:
        """Extract derivation metadata from a data dict, if present."""
        raw = data.get(DerivationTracker.METADATA_KEY)
        if raw is None:
            return None
        return DerivationMetadata.from_dict(raw)

    @staticmethod
    def get_source(data: Dict) -> Optional[DerivationSource]:
        """Get the derivation source of a data dict."""
        metadata = DerivationTracker.get_metadata(data)
        if metadata is None:
            return None
        try:
            return DerivationSource(metadata.source)
        except ValueError:
            return None

    @staticmethod
    def is_derived(data: Dict) -> bool:
        """Check if a data dict was derived (not manual or default)."""
        source = DerivationTracker.get_source(data)
        if source is None:
            return False
        return source in (
            DerivationSource.QUARK_DERIVED,
            DerivationSource.PHYSICS_DERIVED,
            DerivationSource.AUTO_GENERATED,
        )

    @staticmethod
    def is_manual(data: Dict) -> bool:
        """Check if a data dict was manually entered."""
        source = DerivationTracker.get_source(data)
        return source == DerivationSource.MANUAL

    @staticmethod
    def strip_metadata(data: Dict) -> Dict:
        """Return a copy of data with derivation metadata removed (for export)."""
        result = {k: v for k, v in data.items() if k != DerivationTracker.METADATA_KEY}
        return result

    @staticmethod
    def get_confidence(data: Dict) -> float:
        """Get the confidence score of a data dict. Returns 0.0 if no metadata."""
        metadata = DerivationTracker.get_metadata(data)
        if metadata is None:
            return 0.0
        return metadata.confidence
