//====== periodica/rust/periodica_core/src/export.rs ======//
//!copyright (c) 2025 Andrew Keith Watts. All rights reserved.
//!
//!This is the intellectual property of Andrew Keith Watts. Unauthorized
//!reproduction, distribution, or modification of this code, in whole or in part,
//!without the express written permission of Andrew Keith Watts is strictly prohibited.
//!
//!For inquiries, please contact AndrewKWatts@Gmail.com

//! 3D export pipeline.
//!
//! Mirrors the Python `export_*` API surface:
//! - `export_stl`, `export_obj`, `export_vtk_legacy`, `export_sdf_raw`
//! - `export_hlsl` (legacy DirectX) and the NEW `export_glsl` for GLSL 450+ /
//!   SPIR-V consumers (PlayTowEngine).
//!
//! Wave-2 stub.

use anyhow::{Result, anyhow};

/// Emit a GLSL 450+ source string that contains a `vec4 SampleMaterial_<name>`
/// function returning packed (density, IOR, sss, caustic). The material spec is
/// resolved against the periodica datasheet registry; the returned string is
/// ready to `#include` from a raymarch shader.
///
/// Wave-2 stub — returns a placeholder GLSL that compiles to a shader but
/// always returns zeros. Wave 3 wires up the real per-property emission.
pub fn export_glsl(
    name: &str,
    _include_density: bool,
    _include_ior: bool,
    _include_sss: bool,
    _include_caustic: bool,
) -> Result<String> {
    if name.is_empty() {
        return Err(anyhow!("material name must not be empty"));
    }
    let safe_name: String = name.chars().filter(|c| c.is_ascii_alphanumeric() || *c == '_').collect();
    Ok(format!(
        "// Auto-generated by periodica_core::export::export_glsl (Wave-2 stub)\n\
         vec4 SampleMaterial_{name}(vec3 worldPos, float scaleM) {{\n\
         \treturn vec4(0.0, 1.0, 0.0, 0.0); // density=0, IOR=1, no SSS, no caustic\n\
         }}\n",
        name = safe_name,
    ))
}

/// Emit a raw 3D float32 voxel volume of the SDF (or occupancy) for `name`.
/// Wave-2 stub.
pub fn export_sdf_raw(
    _name: &str,
    _bounds: ((f64, f64, f64), (f64, f64, f64)),
    _voxel_size: f64,
) -> Result<Vec<f32>> {
    Err(anyhow!("export_sdf_raw not yet implemented"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn export_glsl_rejects_empty_name() {
        assert!(export_glsl("", true, true, true, true).is_err());
    }

    #[test]
    fn export_glsl_emits_function_signature() {
        let src = export_glsl("Iron", true, true, true, true).unwrap();
        assert!(src.contains("vec4 SampleMaterial_Iron"));
        assert!(src.contains("vec3 worldPos"));
    }

    #[test]
    fn export_glsl_sanitises_name() {
        let src = export_glsl("Glass-Borosilicate", true, true, true, true).unwrap();
        assert!(src.contains("SampleMaterial_GlassBorosilicate"));
    }
}
