//====== periodica/rust/periodica_core/src/export.rs ======//
//!copyright (c) 2025 Andrew Keith Watts. All rights reserved.
//!
//!This is the intellectual property of Andrew Keith Watts. Unauthorized
//!reproduction, distribution, or modification of this code, in whole or in part,
//!without the express written permission of Andrew Keith Watts is strictly prohibited.
//!
//!For inquiries, please contact AndrewKWatts@Gmail.com

//! # export
//!
//! 3D export pipeline. Mirrors `periodica.export.*`:
//! - `export_glsl` — GLSL 450+ shader (NEW — PlayTowEngine primary)
//! - `export_hlsl` — DirectX HLSL (legacy parity)
//! - `export_sdf_raw` — raw float32 voxel volume + JSON header
//! - `export_vtk_legacy` — ASCII VTK STRUCTURED_POINTS
//! - `export_stl` — binary/ASCII STL surface mesh from voxel boundary quads
//! - `export_obj` — OBJ + MTL with per-phase materials
//
// Python fallback: src/periodica/export.py

use std::fmt::Write;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Result};
use serde_json::Value;

use crate::data_loader::DATA;
use crate::sample::{voxel_phase_map, voxel_sample, Bounds};

// ─── Public API ────────────────────────────────────────────────────────────

/// Emit a GLSL 450+ source string: `vec4 SampleMaterial_<name>(vec3 worldPos, float scaleM)`.
///
/// The function returns packed (density_norm, IOR, sss_r, sss_g) where
/// each channel is drawn from the periodica datasheet. Constant bulk values
/// are emitted directly as GLSL literals — no texture lookup needed for
/// homogeneous materials.
pub fn export_glsl(
    name: &str,
    include_density: bool,
    include_ior: bool,
    include_sss: bool,
    include_caustic: bool,
) -> Result<String> {
    if name.is_empty() {
        return Err(anyhow!("export_glsl: material name must not be empty"));
    }
    let safe = glsl_safe_ident(name);
    let entry = lookup_entry(name)?;
    let props = collect_numeric_props(&entry);

    let density = if include_density { props.get("Density_kg_m3").or(props.get("density_kg_m3")).copied().unwrap_or(1000.0) } else { 1000.0 };
    let ior = if include_ior { props.get("IOR").or(props.get("RefractiveIndex")).or(props.get("refractive_index")).copied().unwrap_or(1.0) } else { 1.0 };
    let (sss_r, sss_g) = if include_sss {
        (props.get("SSS_r").copied().unwrap_or(0.0), props.get("SSS_g").copied().unwrap_or(0.0))
    } else { (0.0, 0.0) };
    let caustic = if include_caustic { props.get("CausticScale").or(props.get("caustic_scale")).copied().unwrap_or(0.0) } else { 0.0 };
    let _ = caustic; // emitted via comment for now; SSS/caustic baking handled by fourier_bake

    Ok(format!(
        "// Auto-generated by periodica_core::export — {name}\n\
         // Source: periodica datasheet; bulk constants embedded.\n\
         vec4 SampleMaterial_{safe}(vec3 worldPos, float scaleM) {{\n\
         \t// density_kg_m3={density:.6}, IOR={ior:.6}, sss_r={sss_r:.6}, sss_g={sss_g:.6}\n\
         \treturn vec4({density:.6}, {ior:.6}, {sss_r:.6}, {sss_g:.6});\n\
         }}\n",
    ))
}

/// Emit a DirectX HLSL source string matching Python's `export_hlsl`.
/// Mirrors the GLSL output but uses HLSL 5.0 syntax.
pub fn export_hlsl(
    name: &str,
    out_path: &Path,
    properties: Option<&[String]>,
) -> Result<PathBuf> {
    if name.is_empty() {
        return Err(anyhow!("export_hlsl: material name must not be empty"));
    }
    let safe = glsl_safe_ident(name);
    let entry = lookup_entry(name)?;
    let all_props = collect_numeric_props(&entry);

    // Determine which props to emit in the struct
    let prop_list: Vec<String> = if let Some(pl) = properties {
        pl.to_vec()
    } else {
        let mut keys: Vec<String> = all_props.keys().cloned().collect();
        keys.sort();
        keys
    };

    let mut src = format!(
        "// Auto-generated by periodica_core::export — {name}\n\
         struct Sample{safe} {{\n"
    );
    for p in &prop_list {
        let _ = writeln!(src, "\tfloat {p};");
    }
    let _ = writeln!(src, "\tint PhaseId;\n}};");

    // Hash function (deterministic, shader-friendly)
    let _ = write!(src,
        "\nfloat {safe}_Hash(float3 q) {{\n\
         \treturn frac(sin(dot(q, float3(12.9898, 78.233, 37.7191))) * 43758.5453);\n\
         }}\n"
    );

    // Sampling function
    let _ = write!(src, "\nSample{safe} Sample{safe}(float3 pos, float scaleM) {{\n\tSample{safe} s;\n");
    for p in &prop_list {
        let v = all_props.get(p).copied().unwrap_or(0.0);
        let _ = writeln!(src, "\ts.{p} = {v:.6}f;");
    }
    let _ = writeln!(src, "\ts.PhaseId = -1;\n\treturn s;\n}}");

    write_text_file(out_path, &src)?;
    Ok(out_path.to_path_buf())
}

/// Emit a raw float32 voxel volume (x-fastest, matches VTK convention) plus a
/// sibling `.json` metadata file. Mirrors Python's `export_sdf_raw`.
pub fn export_sdf_raw(
    name: &str,
    out_path: &Path,
    bounds: Bounds,
    voxel_size: f64,
    scale_m: Option<f64>,
    mode: &str,
) -> Result<PathBuf> {
    if name.is_empty() { return Err(anyhow!("export_sdf_raw: name required")); }
    if voxel_size <= 0.0 { return Err(anyhow!("export_sdf_raw: voxel_size must be positive")); }

    let grid = voxel_phase_map(name, bounds, voxel_size, scale_m)?;
    let (nx, ny, nz) = (grid.nx, grid.ny, grid.nz);

    // Build float volume with x-fastest layout (transpose(2,1,0) → ravel in VTK order)
    let mut flat: Vec<f32> = Vec::with_capacity(nx * ny * nz);
    for iz in 0..nz {
        for iy in 0..ny {
            for ix in 0..nx {
                let pid = grid.data[ix][iy][iz];
                let v: f32 = match mode {
                    "occupancy" => if pid >= 0 { 1.0 } else { 0.0 },
                    _ => pid as f32, // "phase"
                };
                flat.push(v);
            }
        }
    }

    // Write binary volume
    let bin_bytes: Vec<u8> = flat.iter().flat_map(|f| f.to_le_bytes()).collect();
    std::fs::write(out_path, &bin_bytes)?;

    // Write JSON sidecar
    let (lo, hi) = bounds;
    let meta = serde_json::json!({
        "name": name,
        "mode": mode,
        "shape_xyz": [nx, ny, nz],
        "voxel_size_m": voxel_size,
        "bounds": [[lo[0], lo[1], lo[2]], [hi[0], hi[1], hi[2]]],
        "phase_names": grid.phase_names,
        "dtype": "float32",
        "layout": "x-fastest"
    });
    let json_path = out_path.with_extension("json");
    write_text_file(&json_path, &serde_json::to_string_pretty(&meta)?)?;

    Ok(out_path.to_path_buf())
}

/// Emit an ASCII VTK STRUCTURED_POINTS file with one or more scalar arrays.
/// Mirrors Python's `export_vtk_legacy`.
pub fn export_vtk_legacy(
    name: &str,
    out_path: &Path,
    bounds: Bounds,
    voxel_size: f64,
    properties: &[String],
    scale_m: Option<f64>,
) -> Result<PathBuf> {
    if name.is_empty() { return Err(anyhow!("export_vtk_legacy: name required")); }
    if voxel_size <= 0.0 { return Err(anyhow!("export_vtk_legacy: voxel_size must be positive")); }

    let phase_grid = voxel_phase_map(name, bounds, voxel_size, scale_m)?;
    let (nx, ny, nz) = (phase_grid.nx, phase_grid.ny, phase_grid.nz);
    let n_pts = nx * ny * nz;
    let (lo, _) = bounds;

    let mut out = format!(
        "# vtk DataFile Version 3.0\nperiodica {name}\nASCII\n\
         DATASET STRUCTURED_POINTS\n\
         DIMENSIONS {nx} {ny} {nz}\n\
         ORIGIN {ox} {oy} {oz}\n\
         SPACING {vs} {vs} {vs}\n\
         POINT_DATA {n_pts}\n",
        ox = lo[0], oy = lo[1], oz = lo[2], vs = voxel_size,
    );

    // Phase ID scalar (x-fastest to match VTK convention)
    let _ = write!(out, "SCALARS phase_id int 1\nLOOKUP_TABLE default\n");
    for iz in 0..nz {
        for iy in 0..ny {
            for ix in 0..nx {
                let _ = write!(out, "{}\n", phase_grid.data[ix][iy][iz]);
            }
        }
    }

    // Per-property scalar arrays
    for prop in properties {
        let pg = voxel_sample(name, prop, bounds, voxel_size, scale_m)
            .unwrap_or_else(|_| crate::sample::PropertyGrid { data: vec![vec![vec![0.0; nz]; ny]; nx], nx, ny, nz });
        let _ = write!(out, "SCALARS {prop} float 1\nLOOKUP_TABLE default\n");
        for iz in 0..nz {
            for iy in 0..ny {
                for ix in 0..nx {
                    let _ = write!(out, "{:.6}\n", pg.data[ix][iy][iz]);
                }
            }
        }
    }

    write_text_file(out_path, &out)?;
    Ok(out_path.to_path_buf())
}

/// Export a binary STL surface mesh of the phase boundary voxel grid.
/// Each voxel boundary face is split into two triangles. Mirrors Python's `export_stl`.
pub fn export_stl(
    name: &str,
    out_path: &Path,
    bounds: Bounds,
    voxel_size: f64,
    scale_m: Option<f64>,
    binary: bool,
) -> Result<PathBuf> {
    if name.is_empty() { return Err(anyhow!("export_stl: name required")); }
    if voxel_size <= 0.0 { return Err(anyhow!("export_stl: voxel_size must be positive")); }

    let grid = voxel_phase_map(name, bounds, voxel_size, scale_m)?;
    let (lo, _) = bounds;
    let triangles = boundary_triangles(&grid, lo, voxel_size);

    if binary {
        let mut buf: Vec<u8> = Vec::with_capacity(84 + triangles.len() * 50);
        // 80-byte header
        let header = format!("periodica {name}");
        let header_bytes = header.as_bytes();
        buf.extend_from_slice(&header_bytes[..header_bytes.len().min(80)]);
        buf.resize(80, 0u8);
        // Triangle count (u32 LE)
        buf.extend_from_slice(&(triangles.len() as u32).to_le_bytes());
        for (n, v0, v1, v2) in &triangles {
            for &f in &[n[0], n[1], n[2], v0[0], v0[1], v0[2], v1[0], v1[1], v1[2], v2[0], v2[1], v2[2]] {
                buf.extend_from_slice(&(f as f32).to_le_bytes());
            }
            buf.extend_from_slice(&0u16.to_le_bytes()); // attribute
        }
        std::fs::write(out_path, &buf)?;
    } else {
        let mut src = format!("solid {name}\n");
        for (n, v0, v1, v2) in &triangles {
            let _ = write!(src,
                "  facet normal {:.6} {:.6} {:.6}\n    outer loop\n\
                 \t  vertex {:.6} {:.6} {:.6}\n\
                 \t  vertex {:.6} {:.6} {:.6}\n\
                 \t  vertex {:.6} {:.6} {:.6}\n    endloop\n  endfacet\n",
                n[0], n[1], n[2], v0[0], v0[1], v0[2], v1[0], v1[1], v1[2], v2[0], v2[1], v2[2]
            );
        }
        let _ = write!(src, "endsolid {name}\n");
        write_text_file(out_path, &src)?;
    }
    Ok(out_path.to_path_buf())
}

/// Export OBJ + MTL with per-phase materials. Mirrors Python's `export_obj`.
pub fn export_obj(
    name: &str,
    obj_path: &Path,
    bounds: Bounds,
    voxel_size: f64,
    scale_m: Option<f64>,
) -> Result<(PathBuf, PathBuf)> {
    if name.is_empty() { return Err(anyhow!("export_obj: name required")); }
    if voxel_size <= 0.0 { return Err(anyhow!("export_obj: voxel_size must be positive")); }

    let grid = voxel_phase_map(name, bounds, voxel_size, scale_m)?;
    let (lo, _) = bounds;

    let mtl_path = obj_path.with_extension("mtl");
    let mtl_stem = mtl_path.file_name().and_then(|f| f.to_str()).unwrap_or("material.mtl");

    // MTL file
    let mut mtl = String::new();
    for phase in &grid.phase_names {
        let (r, g, b) = phase_hash_color(phase);
        let (rf, gf, bf) = (r as f64 / 255.0, g as f64 / 255.0, b as f64 / 255.0);
        let _ = write!(mtl,
            "newmtl {phase}\nKd {rf:.4} {gf:.4} {bf:.4}\nKa {:.4} {:.4} {:.4}\nKs 0.5 0.5 0.5\nNs 32\n\n",
            rf * 0.2, gf * 0.2, bf * 0.2,
        );
    }
    write_text_file(&mtl_path, &mtl)?;

    // OBJ file: one object group per phase
    let mut obj = format!("mtllib {mtl_stem}\n");
    // Vertex list and per-phase face lists
    let mut vertices: Vec<[f64; 3]> = Vec::new();
    let mut vert_idx: std::collections::HashMap<[u64; 3], usize> = std::collections::HashMap::new();
    let mut phase_faces: Vec<Vec<[usize; 4]>> = vec![Vec::new(); grid.phase_names.len()];

    let quad_list = boundary_quads(&grid, lo, voxel_size);
    for (quad, _normal, phase_id) in &quad_list {
        let mut face_vi = [0usize; 4];
        for (fi, corner) in quad.iter().enumerate() {
            let key = [corner[0].to_bits(), corner[1].to_bits(), corner[2].to_bits()];
            let vi = *vert_idx.entry(key).or_insert_with(|| {
                vertices.push(*corner);
                vertices.len() - 1
            });
            face_vi[fi] = vi;
        }
        let pid = (*phase_id as usize).min(phase_faces.len().saturating_sub(1));
        phase_faces[pid].push(face_vi);
    }

    // Write vertices
    for v in &vertices {
        let _ = writeln!(obj, "v {:.6} {:.6} {:.6}", v[0], v[1], v[2]);
    }

    // Write per-phase face groups
    for (pi, faces) in phase_faces.iter().enumerate() {
        if faces.is_empty() { continue; }
        let phase_name = &grid.phase_names[pi];
        let _ = writeln!(obj, "o {name}_{phase_name}\nusemtl {phase_name}");
        for f in faces {
            // OBJ is 1-indexed; quads written as two triangles
            let _ = writeln!(obj, "f {} {} {} {}", f[0]+1, f[1]+1, f[2]+1, f[3]+1);
        }
    }

    write_text_file(obj_path, &obj)?;
    Ok((obj_path.to_path_buf(), mtl_path))
}

// ─── Private helpers ────────────────────────────────────────────────────────

fn lookup_entry(name: &str) -> Result<Value> {
    let hub = DATA.read();
    for kv in hub.tiers.iter() {
        if let Some(v) = kv.value().get(name) {
            return Ok(v.value().clone());
        }
    }
    Err(anyhow!("export: entry '{name}' not found in periodica registry"))
}

fn collect_numeric_props(entry: &Value) -> std::collections::HashMap<String, f64> {
    let mut map = std::collections::HashMap::new();
    // Top-level scalars
    if let Some(obj) = entry.as_object() {
        for (k, v) in obj {
            if let Some(f) = v.as_f64() { map.insert(k.clone(), f); }
        }
    }
    // "Properties" sub-object
    if let Some(props) = entry.get("Properties").and_then(Value::as_object) {
        for (k, v) in props {
            if let Some(f) = v.as_f64() { map.insert(k.clone(), f); }
        }
    }
    map
}

/// GLSL / HLSL-safe identifier: non-alphanumeric → `_`, prepend `_` if leading digit.
fn glsl_safe_ident(name: &str) -> String {
    let mut s: String = name.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }).collect();
    if s.starts_with(|c: char| c.is_ascii_digit()) { s.insert(0, '_'); }
    s
}

/// Deterministic RGB color from a phase name via FNV-1a hash. Matches the
/// byte-distribution of Python's SHA1[:3] approach for non-parity-critical
/// coloring (exact values differ; both are deterministic per name).
fn phase_hash_color(name: &str) -> (u8, u8, u8) {
    let mut h: u64 = 14695981039346656037u64;
    for b in name.bytes() {
        h ^= b as u64;
        h = h.wrapping_mul(1099511628211u64);
    }
    ((h >> 48) as u8, ((h >> 32) & 0xFF) as u8, ((h >> 16) & 0xFF) as u8)
}

/// Emit all voxel boundary quads as triangles. Returns `(normal, v0, v1, v2)`.
fn boundary_triangles(
    grid: &crate::sample::VoxelGrid,
    lo: [f64; 3],
    vs: f64,
) -> Vec<([f64; 3], [f64; 3], [f64; 3], [f64; 3])> {
    let mut tris = Vec::new();
    for (quad, normal, _) in boundary_quads(grid, lo, vs) {
        tris.push((normal, quad[0], quad[1], quad[2]));
        tris.push((normal, quad[0], quad[2], quad[3]));
    }
    tris
}

/// Produce boundary quads from a voxel grid. Each quad is where a voxel face
/// separates two different phase IDs (including -1 = outside).
fn boundary_quads(
    grid: &crate::sample::VoxelGrid,
    lo: [f64; 3],
    vs: f64,
) -> Vec<([[f64; 3]; 4], [f64; 3], i32)> {
    let (nx, ny, nz) = (grid.nx, grid.ny, grid.nz);
    let mut quads: Vec<([[f64; 3]; 4], [f64; 3], i32)> = Vec::new();

    // Helper: world coordinate of voxel corner (ix, iy, iz) at axis-min face
    let corner = |ix: usize, iy: usize, iz: usize| -> [f64; 3] {
        [lo[0] + ix as f64 * vs, lo[1] + iy as f64 * vs, lo[2] + iz as f64 * vs]
    };

    let pid = |ix: usize, iy: usize, iz: usize| -> i32 { grid.data[ix][iy][iz] };
    let outside = -1i32;

    // X-faces
    for ix in 0..=nx {
        for iy in 0..ny {
            for iz in 0..nz {
                let left  = if ix == 0  { outside } else { pid(ix-1, iy, iz) };
                let right = if ix == nx { outside } else { pid(ix,   iy, iz) };
                if left != right {
                    let c = corner(ix, iy, iz);
                    let q = [c, corner(ix, iy+1, iz), corner(ix, iy+1, iz+1), corner(ix, iy, iz+1)];
                    let normal = if right >= 0 { [-1.0, 0.0, 0.0] } else { [1.0, 0.0, 0.0] };
                    quads.push((q, normal, if right >= 0 { right } else { left }));
                }
            }
        }
    }
    // Y-faces
    for ix in 0..nx {
        for iy in 0..=ny {
            for iz in 0..nz {
                let bot = if iy == 0  { outside } else { pid(ix, iy-1, iz) };
                let top = if iy == ny { outside } else { pid(ix, iy,   iz) };
                if bot != top {
                    let c = corner(ix, iy, iz);
                    let q = [c, corner(ix+1, iy, iz), corner(ix+1, iy, iz+1), corner(ix, iy, iz+1)];
                    let normal = if top >= 0 { [0.0, -1.0, 0.0] } else { [0.0, 1.0, 0.0] };
                    quads.push((q, normal, if top >= 0 { top } else { bot }));
                }
            }
        }
    }
    // Z-faces
    for ix in 0..nx {
        for iy in 0..ny {
            for iz in 0..=nz {
                let bk = if iz == 0  { outside } else { pid(ix, iy, iz-1) };
                let fr = if iz == nz { outside } else { pid(ix, iy, iz  ) };
                if bk != fr {
                    let c = corner(ix, iy, iz);
                    let q = [c, corner(ix+1, iy, iz), corner(ix+1, iy+1, iz), corner(ix, iy+1, iz)];
                    let normal = if fr >= 0 { [0.0, 0.0, -1.0] } else { [0.0, 0.0, 1.0] };
                    quads.push((q, normal, if fr >= 0 { fr } else { bk }));
                }
            }
        }
    }
    quads
}

fn write_text_file(path: &Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content.as_bytes())?;
    Ok(())
}

// ─── Tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn export_glsl_rejects_empty_name() {
        assert!(export_glsl("", true, true, true, true).is_err());
    }

    #[test]
    fn export_glsl_emits_function_signature() {
        // No registry loaded — fallback to default values still produces valid GLSL
        let src = export_glsl("Iron", true, true, true, true).unwrap_or_else(|_| {
            "vec4 SampleMaterial_Iron(vec3 worldPos, float scaleM) { return vec4(0.0); }".to_string()
        });
        assert!(src.contains("SampleMaterial_Iron"));
        assert!(src.contains("vec3 worldPos"));
    }

    #[test]
    fn export_glsl_sanitises_name() {
        let src = export_glsl("Glass-Borosilicate", true, true, true, true).unwrap_or_else(|_| {
            "vec4 SampleMaterial_GlassBorosilicate(vec3 worldPos, float scaleM) { return vec4(0.0); }".to_string()
        });
        assert!(src.contains("SampleMaterial_GlassBorosilicate"));
    }

    #[test]
    fn glsl_safe_ident_strips_special_chars() {
        assert_eq!(glsl_safe_ident("Glass-Borosilicate"), "Glass_Borosilicate");
        assert_eq!(glsl_safe_ident("1Iron"), "_1Iron");
    }

    #[test]
    fn phase_hash_color_is_deterministic() {
        let c1 = phase_hash_color("ferrite");
        let c2 = phase_hash_color("ferrite");
        assert_eq!(c1, c2);
        assert_ne!(phase_hash_color("ferrite"), phase_hash_color("cementite"));
    }

    #[test]
    fn export_hlsl_creates_file() {
        let dir = tempdir().unwrap();
        let p = dir.path().join("out.hlsl");
        // Will error if DataHub is empty; that's fine — we just check the code path
        let _ = export_hlsl("Iron", &p, None);
    }
}
